version: "2"

services:

  web:
    build: .
    image: ctftraining/xctf_2019_final_web_lfi
    restart: always
    ports:
      - "127.0.0.1:8302:80"
    environment:
      - FLAG=flag{glzjin_wants_a_girl_firend}
